version: '3.8'
services:
  postgresql:
    container_name: postgresql
    image: postgres:15.1-alpine
    ports:
      - ${DB_PORT}:5432
    volumes:
      - db-data:/var/lib/postgresql/data # db-dataは名前
      - ./docker/postgresql/data:/docker-entrypoint-initdb.d
    environment:
      POSTGRES_DB: ${DB_DATABASE}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_INITDB_ARGS: '--encoding=UTF-8'
    build:
      context: .
      dockerfile: ./docker/postgresql/Dockerfile
  app:
    container_name: ${APP_CONTAINER_NAME}
    build:
      context: .
      dockerfile: ./Dockerfile
    environment:
      - GOPATH=/go
      - DB_HOST=postgresql
      - SERVER_HOST=0.0.0.0
    volumes:
      - .:/app
      - .env:/app/.env
    ports:
      - ${APP_PORT}:8080
    tty: true
    depends_on:
      - postgresql
volumes:
  db-data:
