version: '3.8'
services:
  postgresql:
    container_name: ${DB_HOST}
    image: postgres:15.1-alpine
    ports:
      - ${DB_PORT}:5432
    volumes:
      - db-data:/var/lib/postgresql/data # db-dataは名前
      - ./docker/postgresql/data:/docker-entrypoint-initdb.d
    environment:
      POSTGRES_DB: ${DB_DATABASE}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_INITDB_ARGS: '--encoding=UTF-8'
    hostname: postgres
    user: postgres
    build:
      context: .
      dockerfile: docker/postgresql/Dockerfile
  app:
    container_name: app
    environment:
      - GOPATH=/go
      - DB_HOST=postgresql
      - SERVER_HOST=localhost
    build:
      context: .
      dockerfile: ./Dockerfile
    volumes:
      - .:/app
      - .env:/app/.env
    ports:
      - '8000:8080'
    tty: true
    depends_on:
      - postgresql
volumes:
  db-data:
